### ISSUE TITLE
Missing Required Parameter Error

### ISSUE THREAD

**Issue by KayBeSee** [Exeu/Amazon-ECS-PHP-Library#33]
Hey Jan --

I am just experimenting with this code to build a web application for my site. I am not the most experienced coder, but have done some work with Wordpress and PHP in the past. I have edited the "sampleSettings.php" and placed it in the same directory as the file I am working on and also have "lib/AmazonECS.class.php" linked correctly with all the correct IDs, Tags, etc inputted.

When I use the following source code:

<?php

  include 'sampleSettings.php';

defined('AWS_API_KEY') or define('AWS_API_KEY', 'API KEY');
defined('AWS_API_SECRET_KEY') or define('AWS_API_SECRET_KEY', 'SECRET KEY');

require_once '../lib/AmazonECS.class.php';

```
// get a new object with your API Key and secret key. Lang is optional.
// if you leave lang blank it will be US.
$amazonEcs = new AmazonECS(AWS_API_KEY, AWS_API_SECRET_KEY, 'us', AWS_ASSOCIATE_TAG);

//$amazonEcs->returnType(AmazonECS::RETURN_TYPE_ARRAY);

// changing the category to DVD and the response to only images and looking for some matrix stuff.
$response = $amazonEcs->category('DVD')->responseGroup('Images')->country('us')->search("Matrix Revolutions");
var_dump($response);
```

catch(Exception $e)
{
  echo $e->getMessage();
}

I get this result printed:

 <pre>
array(2) {
  ["OperationRequest"]=>
  array(4) {
    ["HTTPHeaders"]=>
    array(1) {
      ["Header"]=>
      array(2) {
        ["Name"]=>
        string(9) "UserAgent"
        ["Value"]=>
        string(14) "PHP-SOAP/5.3.1"
      }
    }
    ["RequestId"]=>
    string(36) "3cf95c06-31e7-432f-9bf5-2626e1c212c3"
    ["Arguments"]=>
    array(1) {
      ["Argument"]=>
      array(2) {
        ["Name"]=>
        string(7) "Service"
        ["Value"]=>
        string(19) "AWSECommerceService"
      }
    }
    ["RequestProcessingTime"]=>
    float(0.002351)
  }
  ["Items"]=>
  array(1) {
    ["Request"]=>
    array(3) {
      ["IsValid"]=>
      string(5) "False"
      ["ItemSearchRequest"]=>
      array(3) {
        ["Keywords"]=>
        string(18) "Matrix Revolutions"
        ["ResponseGroup"]=>
        string(6) "Images"
        ["SearchIndex"]=>
        string(3) "DVD"
      }
      ["Errors"]=>
      array(1) {
        ["Error"]=>
        array(2) {
          ["Code"]=>
          string(21) "AWS.MissingParameters"
          ["Message"]=>
          string(86) "Your request is missing required parameters. Required parameters include AssociateTag."
        }
      }
    }
  }
} 
</pre>

It saids I am missing the required parameter "AssociateTag" but that setting is inputted in the settings file twice (Associate_Tag & Another_Associate_Tag). Can you help me out and maybe explain what I am doing wrong? I would really appreciate it.

Also, I apologize for the wall of code.

**Comment by Exeu** [comment]
Hi,
since newer versions of the amazon api the so called Associate Tag is required to pass it with the request.
If you are using a newer version of this class (1.3.3) you can see that the fourth parameter of the constructor is required.
This is the associate Tag you have to set.

For example:
$amazonEcs = new AmazonECS("mySecretKey", "myApiKey", 'us', "myAssociateTag");

if you don't have an associate tag you can provide a string like "aaaaabbbbcccc" to get it working.

To recieve a valid associate Tag and to get information about what it is please have a look into the documentation of the amazon api.

http://docs.amazonwebservices.com/AWSECommerceService/latest/DG/CommonRequestParameters.html#CommonRequestParameters_AssociateTag

and here:
http://docs.amazonwebservices.com/AWSECommerceService/latest/DG/becomingAssociate.html

i hope this was helpfull.
