### ISSUE TITLE
Amazon Associates

### ISSUE THREAD

**Issue by samedney** [Exeu/Amazon-ECS-PHP-Library#8]
I have been trying to get a decent PHP Amazon search working for a very long time - this does the job perfectly (or at least it seems to - I havent worked out the parsing yet). 

One obvious thing missing is the ability to add an associate ID - is this possible?

**Comment by Exeu** [comment]
Hi,
thank you for your feedback!

Of course this is an very needed feature.
I will implement this and creating a new release soon.

**Comment by Exeu** [comment]
Version 1.0 is out right now.
With this version of the library you should be able to set up the Associate ID.

Please see the new testfile: testAssociateTag.php for more information.
The Documentation comes soon.

**Comment by samedney** [comment]
This is really great now. Thank you for looking at it so quickly. I have added a Wiki page that might help people get started. Maybe if you have time you could take a look and let me know if there are better ways for me to access this data.

Thank you so much for saving me a heck of a lot of time.

**Comment by Exeu** [comment]
Hi,
i looked at your page and noticed that you used "Large" as response group.
I don't know if this makes sense here because you access just a hand full of data.
Try to use combined Responsegroups like "Small,Images".
This would save a lot of bandwith.

The way of accessing the dara looks quite good.
Notice that there is no other way to access them because this 1:1 this what you get from Amazon self.

**Comment by samedney** [comment]
The associate ID isnt picked up when ordering. Just placed an order and it didnt show up on my associate account, though items ordered with my previous method did work.

I think it might be due to the URL being fully encoded - so that the tag=XXX isnt showing correctly.

Can you check it out?

--Edit-- I have just re-ordered using the old method and it still is not showing. Maybe it just takes time to show up. Will let you know.
